# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 687)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(20, 20, 151, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.sendbutton = QtWidgets.QPushButton(self.centralwidget)
        self.sendbutton.setGeometry(QtCore.QRect(20, 330, 99, 27))
        self.sendbutton.setObjectName("sendbutton")
        self.reciever = QtWidgets.QLineEdit(self.centralwidget)
        self.reciever.setGeometry(QtCore.QRect(20, 70, 113, 27))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.reciever.setFont(font)
        self.reciever.setObjectName("reciever")
        self.massage_text = QtWidgets.QTextEdit(self.centralwidget)
        self.massage_text.setGeometry(QtCore.QRect(20, 130, 331, 181))
        self.massage_text.setObjectName("massage_text")
        self.chat_window = QtWidgets.QTextBrowser(self.centralwidget)
        self.chat_window.setGeometry(QtCore.QRect(540, 10, 351, 621))
        self.chat_window.setObjectName("chat_window")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(20, 50, 91, 17))
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(20, 110, 141, 17))
        self.label2.setObjectName("label2")
        self.startbutton = QtWidgets.QPushButton(self.centralwidget)
        self.startbutton.setGeometry(QtCore.QRect(180, 410, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.startbutton.setFont(font)
        self.startbutton.setObjectName("startbutton")
        self.contacts_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.contacts_comboBox.setGeometry(QtCore.QRect(390, 30, 141, 31))
        self.contacts_comboBox.setObjectName("contacts_comboBox")
        self.current_chat_label = QtWidgets.QLabel(self.centralwidget)
        self.current_chat_label.setGeometry(QtCore.QRect(390, 10, 91, 17))
        self.current_chat_label.setObjectName("current_chat_label")
        self.contacts_list = QtWidgets.QListWidget(self.centralwidget)
        self.contacts_list.setGeometry(QtCore.QRect(390, 100, 121, 151))
        self.contacts_list.setMouseTracking(False)
        self.contacts_list.setObjectName("contacts_list")
        self.nick_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nick_lineEdit.setGeometry(QtCore.QRect(180, 520, 151, 31))
        self.nick_lineEdit.setObjectName("nick_lineEdit")
        self.start_nick_label = QtWidgets.QLabel(self.centralwidget)
        self.start_nick_label.setGeometry(QtCore.QRect(180, 500, 131, 17))
        self.start_nick_label.setObjectName("start_nick_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 898, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Сообщение"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Выход"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Новый элемент"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Новый элемент"))
        self.sendbutton.setText(_translate("MainWindow", "Отправить"))
        self.label1.setText(_translate("MainWindow", "Получатель:"))
        self.label2.setText(_translate("MainWindow", "Текст сообщения:"))
        self.startbutton.setText(_translate("MainWindow", "Старт"))
        self.current_chat_label.setText(_translate("MainWindow", "Выбор чата:"))
        self.start_nick_label.setText(_translate("MainWindow", "Введите свой ник:"))
