# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 687)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(20, 20, 151, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.sendbutton = QtWidgets.QPushButton(self.centralwidget)
        self.sendbutton.setGeometry(QtCore.QRect(20, 330, 99, 27))
        self.sendbutton.setObjectName("sendbutton")
        self.reciever = QtWidgets.QLineEdit(self.centralwidget)
        self.reciever.setGeometry(QtCore.QRect(20, 70, 113, 27))
        self.reciever.setObjectName("reciever")
        self.massage_text = QtWidgets.QTextEdit(self.centralwidget)
        self.massage_text.setGeometry(QtCore.QRect(20, 130, 331, 181))
        self.massage_text.setObjectName("massage_text")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(540, 10, 351, 621))
        self.textBrowser.setObjectName("textBrowser")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(20, 50, 91, 17))
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(20, 110, 141, 17))
        self.label2.setObjectName("label2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 898, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Сообщение"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Выход"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Новый элемент"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Новый элемент"))
        self.sendbutton.setText(_translate("MainWindow", "Отправить"))
        self.label1.setText(_translate("MainWindow", "Получатель:"))
        self.label2.setText(_translate("MainWindow", "Текст сообщения:"))
